services:
  - type: web
    name: todolist-backend
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 